apps/store/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views



urlpatterns = [
    url(r'^home.html$', views.product_list, name='product_list'),
    url(r'^delete_all_cart_items/$', views.delete_all_cart_items, name='delete_all_cart_items'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login'}, name='logout'),
    url(r'^carrito_detalle/$', views.carrito_detalle, name='carrito_detalle'),
    path(r'^agregar_producto/(<int:producto_id>)/$', views.agregar_producto, name='agregar_producto'),
    path(r'^delete_cart_item/(<int:producto_id>)/', views.delete_cart_item, name='delete_cart_item'),
    path('<int:producto_id>/', views.detail, name='detail'),
    path('<int:producto_id>/', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<category_slug>[-\w]+)/$',views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),

]

    

mysite/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('apps/store', include('apps.store.urls')),
    path('admin/', admin.site.urls),
    path('apps/store', admin.site.urls),
    #path('apps/store', include('apps.store.urls')),
    
    url(r'^', include(('apps.store.urls', 'store'), namespace='store')),
    path('login/',  include('apps.store.urls')),
    
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/store/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.dispatch import receiver



'''class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,unique=True)

'''
class Categoria(models.Model):
        descripcion = models.CharField(max_length = 100, db_index = True)
        slug = models.SlugField(max_length = 100, db_index = True)

        class Meta:
                ordering =('descripcion',)
                verbose_name = 'categoria'
                verbose_name_plural = 'categorias'

        def __str__(self):
                return self.descripcion

        def get_absolute_url(self):
                return reverse('store:product_list_by_category',args=[self.slug])

class Producto(models.Model):
        nombre = models.CharField(max_length = 50, db_index = True)
        descripcion = models.CharField(max_length = 250)
        precio = models.DecimalField(max_digits = 10,decimal_places = 2)
        oferta = models.BooleanField()
        codigo = models.IntegerField()
        stock = models.PositiveIntegerField(default=0)
        slug = models.SlugField(max_length = 50, db_index = True)
        idCategoria = models.ForeignKey(Categoria, on_delete = models.CASCADE)
        imagen = models.ImageField(upload_to='products/%Y/%m/%d', blank = True)
        
        class Meta:
                ordering = ('-nombre',)
                index_together = (('id','slug'),)

        def __str__(self):
                return self.nombre

        def get_absolute_url(self):
                return reverse('store:product_detail',args = [self.id,self.slug])

class Carrito(models.Model):
        idUsuario = models.ForeignKey(User, on_delete = models.CASCADE, null=True)

class Carrito_Detalle(models.Model):
        idCarrito = models.ForeignKey(Carrito, on_delete = models.CASCADE)
        idProducto = models.ForeignKey(Producto, on_delete = models.CASCADE)
        cantidad = models.IntegerField()



class Historial(models.Model):
        idUsuario = models.ForeignKey(User, on_delete = models.CASCADE)
        fecha = models.DateField()


class Historial_Detalle(models.Model):
        idHistorial = models.ForeignKey(Historial, on_delete = models.CASCADE)
        idProducto = models.ForeignKey(Producto, on_delete = models.CASCADE)
        cantidad = models.IntegerField()


        '''
models.CASCADE)
Cascade deletes. Django emulates the behavior of the SQL 
constraint ON DELETE CASCADE and also deletes the object containing the ForeignKey.
        '''

apps/store/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

'''
class SignUpForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')
    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(SignUpForm, self).save(commit=False)
        user_profile = UserProfile(user=user)
        user.save()
        user_profile.save()
        return user, user_profile'''

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

apps/store/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import  authenticate
from django.contrib.auth import login as auth_login
from django.http import HttpResponse
from .models import Producto,Categoria, Carrito, Carrito_Detalle, Historial, Historial_Detalle
from django.views import generic
from .forms import SignUpForm
from django.views.decorators.csrf import csrf_protect
import datetime
# Create your views here.



@login_required
def index(request):
    product_list = Producto.objects.order_by('-id')
    historial_list = Historial.objects.filter(idUsuario = request.user)
    context = {'product_list': product_list, 'historial_list': historial_list}
    return render(request, 'store/index.html', context)
    #return render(request, 'store/image_test.html', context)

 
def home(request):
    return render(request, 'home.html')


def product_list(request,category_slug = None):
    categoria = None
    categorias = Categoria.objects.all()
    productos = Producto.objects.filter(stock__gt = 0)
    histo = Historial.objects.filter(idUsuario = request.user)
    fechas = []
    historial = []
    for i in histo:
        fechas += [i]
        historial += Historial_Detalle.objects.filter(idHistorial = i)
    if category_slug:
        categoria = get_object_or_404(Categoria,slug = category_slug)
        productos = productos.filter(idCategoria = categoria)

    return render(request,'store/index.html',{'idCategoria':categoria,
                                                            'categorias':categorias,
                                                            'productos':productos,
                                              'historial': historial, 'fechas': fechas})


def product_detail(request,id,slug):
    producto = get_object_or_404(Producto, id = id,slug = slug, stock__gt=0)
    
    return render(request,
                    'apps/store/producto/detail.html',
                    {'producto':producto})


def shopping_cart_list(request):
    userID = request.user.id
    shopping_cart = get_object_or_404(Carrito,idUsuario = userID)
    cart_details = Carrito_Detalle.objects.filter(idCarrito = shopping_cart.id)
    productos = []
    for detail in cart_details:
        productos += get_object_or_404(Producto,id = detail.idProducto)
    return render(request,'apps/store/shopping_cart.html',{'productos':productos})


'''def shopping_cart_list(request):
    userID = request.user.id
    shopping_cart = get_object_or_404(Carrito,idUsuario = userID)
    cart_details = Carrito_Detalle.objects.filter(idCarrito = shopping_cart.id)
    productos = get_object_or_404(Producto,id = cart_details.idProducto)
    return render(request,'apps/store/shopping_cart.html',{'productos':productos})
'''


def detail(request, producto_id):
    producto = get_object_or_404(Producto, pk=producto_id)
    return render(request, 'store/detail.html', {'producto': producto})

class DetailView(generic.DetailView):
    model = Producto
    template_name = 'apps/store/detail.html'


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            auth_login(request, user)
            c = Carrito(idUsuario=user)
            c.save()
            return redirect('/home.html')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

'''
def carrito_detalle(request):

    productos = Producto.objects.filter(stock__gt = 0)

    return render(request, 'shopping_cart.html', {'productos': productos})
'''
def carrito_detalle(request):
    userID = request.user.id

    shopping_cart = get_object_or_404(Carrito,idUsuario = userID)
    cart_details = Carrito_Detalle.objects.filter(idCarrito = shopping_cart.id)
    productos = []
    for detail in cart_details:
        productos += [get_object_or_404(Producto,id = detail.idProducto.id)]
    return render(request, 'shopping_cart.html', {'productos': productos})


def agregar_producto(request, producto_id):
    producto = get_object_or_404(Producto, pk=producto_id)
    producto.stock = producto.stock - 1
    producto.save()

    userID = request.user.id
    shopping_cart = get_object_or_404(Carrito,idUsuario = userID)
    cd = Carrito_Detalle(idCarrito=shopping_cart, idProducto=producto, cantidad=1)
    cd.save()
    return redirect('/home.html')

def delete_cart_item(request,producto_id):
    userID= request.user.id
    
    producto = get_object_or_404(Producto, pk=producto_id)
    producto.stock = producto.stock + 1
    producto.save()
    
    shopping_cart = get_object_or_404(Carrito,idUsuario = userID)
    detail = Carrito_Detalle.objects.filter(idCarrito = shopping_cart.id , idProducto = producto_id)
    #detail =get_object_or_404(Carrito_Detalle, idCarrito = shopping_cart.id , idProducto = producto_id)
    for item in detail:
        if item:
            item.delete()
    return redirect('/home.html')

def delete_all_cart_items(request):
    userID= request.user.id
    shopping_cart = get_object_or_404(Carrito,idUsuario = userID)
    h = Historial(idUsuario=request.user, fecha=datetime.date.today())
    h.save()
    
    detail = Carrito_Detalle.objects.all()
    for item in detail:
        if item:
            hd = Historial_Detalle(idHistorial=h, idProducto=item.idProducto, cantidad=1)
            hd.save()
            item.delete()
    return redirect('/home.html')

'''
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Simple is Better Than Complex{% endblock %}</title>
  </head>
  <body>
    <header>
      <h1>My Site</h1>
      {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">logout</a>
      {% else %}
        <a href="{% url 'login' %}">login</a> / <a href="{% url 'signup' %}">signup</a>
      {% endif %}
      <hr>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>
 usar el if user.is_authenticated y cosas asi. 
'''

apps/store/templates/store/base.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<!DOCTYPE html>
<html>
<head>

<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
    margin-bottom: 0
}
li {
    float: left;
}
li a {
    display: inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}
li a:hover:not(.active) {
    background-color: #111;
}
.active {
    background-color: #4CAF50;
}
</style>
  <meta charset="utf-8">
  <title>{% block title %}El Baratico{% endblock %}</title>
</head>
  <header>
    <h1><img class="logo-img" src="/apps/store/static/baraticoCLOUD.gif" alt="El Baratico" width="200"</h1>
  </header>
  <hr>
  <main>
  <div class="grid-container">
  <div class="item1"><ul>
{% if user.is_authenticated %}
      Hi {{ user.username }}!
      <a href="{% url 'logout' %}">Logout</a>
    {% else %}
      <a href="{% url 'login' %}"> Login    </a>
      <a href="{% url 'signup' %}">    Signup </a>
     {% endif %}
 
</ul>
</div>
    {% block content %}
    {% endblock %}
  </main>
  <hr>
</body>
</html>

apps/store/templates/store/detail.html
<ul>
    <li>{{ producto.descripcion }}</li>
</ul>

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">


<!DOCTYPE html>
<html>
<head>


<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
    margin-bottom: 0
}

li {
    float: left;
}

li a {
    display: inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #111;
}

.active {
    background-color: #4CAF50;
}
.logo-img {
	display:inline-block;
    float:left
    position:absolute;
    left:10px;
    top:10px;
    margin: 0px 15px 15px 0px;
    float: left;
}

</style>


</head>
<body>

<div class="grid-container">
  <div class="item1"><ul>
  <li><a href="/home.html">Home</a></li>
  <li><a href="#news">News</a></li>
  <li><a href="#contact">Contact</a></li>
  <li><a href="{% url 'logout' %}">Logout</a></li>>
  <li><a {{ user.get_full_name }}></a></li>
<li style="float:right"><a class="active" 
  href="{% url 'store:carrito_detalle' %}">Shopping Cart
  <img src="/apps/store/static/cart.png" alt="Cart" width="50" height="50"></a></li>
</ul>
<img class="logo-img" src="/apps/store/static/baraticoCLOUD.gif" alt="El Baratico" width="18%" height="50%">
</div>


<body>
	<h1>{{ producto.nombre }}</h1>
	<div class="item"><br>
			<img src="{{producto.imagen.url}}" width="200" height="200">
		</a>
		<font size="5">
		<!--a href="{% url 'store:detail' producto.id %}">{{ producto.nombre }}</a-->
		₡{{ producto.precio }}<br>
        Productos disponibles: {{producto.stock}}

	</div>
    <div class = "item"><br>
		<a href="{% url 'store:agregar_producto' producto.id %}"> Agregar al carrito </a>
    </div>


</html>

apps/store/templates/store/home.html
{% extends 'base.html' %}

{% block content %}
  <h2>Welcome, {{ user.get_full_name }} <small>{{ user.username }}</small>!</h2>
  <p>Your email address: {{ user.email }}</p>
{% endblock %}

apps/store/templates/store/image_test.html
{% if productos %}
    <ul>
    {% for producto in productos %}
        <li><a href="/apps/store/{{ producto.id }}/">{{ producto.nombre }}</a></li>
		<img src="{{producto.imagen.url}}" alt={{producto.nombre}} width="200" height="200">
    {% endfor %}
    </ul>
{% else %}
    <p>No products are available.</p>
{% endif %}

apps/store/templates/store/index.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">


<!DOCTYPE html>
<html>
<head>
<!-------------------------MENU STYLE------------------------>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
    margin-bottom: 0
}
li {
    float: left;
}
li a {
    display: inline-block;
    color: white;
    text-align: center;
    padding: 11px 16px;
    text-decoration: none;
}
li a:hover:not(.active) {
    background-color: #111;
}
.active {
    background-color: #4CAF50;
}
.logo-img {
	display:inline-block;
    float:left
    position:absolute;
    left:1px;
    top:1px;
    margin: 0px 0px 0px 0px;
    float: left;
}
</style>
<!--ND MENU STYLE->



<!-GRID STYLE-->
<style>
.item1 { grid-area: header; }
.item2 { grid-area: menu; }
.item3 { grid-area: main; }
.item4 { grid-area: right; }
.item5 { grid-area: footer; }

.grid-container {
  display: grid;
  grid-template-areas:
    'header header header header header header'
    'menu main main main main main'
    'menu footer footer footer footer footer';
  grid-gap: 1px;
  background-color: rgba(255, 255, 255);
  padding: 10px;
}
.grid-container > div {
  background-color: rgba(255, 255, 255);
  text-align: center;
  padding: 20px 0;
  font-size: 30px;
}
</style>
<!--=-END GRID STYLE-->


<!---PRODUCT GRID STYLE-->
<style>
.grid-container2 {
  display: grid;
  grid-template-columns: auto auto auto;
  background-color: rgba(255, 255, 255);
  padding: 10px;
}
.grid-item2 {
  background-color: rgba(255, 255, 255);
  border: 0px solid rgba(0, 0, 0);
  padding: 20px;
  font-size: 30px;
  text-align: center;
}
</style>
<!---END PRODUCT GRID STYLE-->




</head>
<body>
<!--h2>Bienvenido a El Baratico, {{ user.get_full_name }}!</h2-->
<title>El Baratico Web</title>
<meta name="viewport" content="width=device-width, initial-scale=1 padding-bottom=0">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>
<div class="w3-content w3-display-container">
<div class="w3-display-container mySlides">
  <img src="/apps/store/static/sea_header.JPG" style="width:100%" height="100">
  <div class="w3-display-middle w3-large w3-container w3-padding-16 w3-black">
	{% if user.get_full_name %}
		Bienvenido a El Baratico, {{ user.get_full_name }}
    {% else %}
		Bienvenido a El Baratico, {{ user.get_username }} 
	{% endif %}
  </div>
</div>
</div>



<div class="grid-container">
  <div class="item1"><ul>
  <li><a href="login/store/index.html">Home</a></li>
  <li><a href="#news">News</a></li>
  <li><a href="#contact">Contact</a></li>
  <li><a href="{% url 'logout' %}">Logout</a></li>>
  <li><a {{ user.get_full_name }}></a></li>
  <li style="float:right"><a class="active" 
  href="{% url 'store:carrito_detalle' %}">Shopping Cart
  <img src="/apps/store/static/cart.png" alt="Cart" width="50" height="50"></a></li>
</ul>
</div>


  <div class="item2"><img class="logo-img" src="/apps/store/static/baraticoCLOUD.gif" alt="El Baratico" width="400" height="500"></div>
  <div class="item3"><img class="logo-img" src="/apps/store/static/ProductosBanner6.png" alt="Productos" width="350" height="75"><br></div>  
  <!--div class="item4"><img class="logo-img" src="/apps/store/static/OfertasBanner.png" alt="Productos" width="500" height="100"><br></div-->
  <div class="item5"><div class="grid-container2">
	      {% if productos %}
			{% for producto in productos %}
				{% if not producto.oferta %}
				<div class="grid-item2">
					<a href="{% url 'store:detail' producto.id %}">
						<img src="{{producto.imagen.url}}" alt={{producto.nombre}} width="200" height="200">
					</a><br>
					<a href="{% url 'store:detail' producto.id %}">{{ producto.nombre }}</a>
					₡{{ producto.precio }}
				</div>
				{% else %}
				{% endif %}
			{% endfor %}
		 
	
		{% else %}
			<p>No products are available.</p>
		{% endif %}
		  </div>
  </div>
</div>


<div class="grid-container">
  <div class="item1">
</div>


  <div class="item2"><img class="logo-img" src="/apps/store/static/baraticoCLOUD_NULL.gif" alt="El Baratico" width="400" height="500"></div>
  <div class="item3"><img class="logo-img" src="/apps/store/static/OfertasBanner.png" alt="Productos" width="300" height="50"><br></div>  
  <!--div class="item4"><img class="logo-img" src="/apps/store/static/OfertasBanner.png" alt="Productos" width="500" height="100"><br></div-->
  <div class="item5"><div class="grid-container2">
	      {% if productos %}
			{% for producto in productos %}
				{% if producto.oferta %}
				<div class="grid-item2">
					<a href="{% url 'store:detail' producto.id %}">
						<img src="{{producto.imagen.url}}" alt={{producto.nombre}} width="200" height="200">
					</a><br>
					<a href="{% url 'store:detail' producto.id %}">{{ producto.nombre }}</a>
					₡{{ producto.precio }}
				</div>
				{% else %}
				{% endif %}
			{% endfor %}
		 
	
		{% else %}
			<p>No products are available.</p>
		{% endif %}
		  </div>
  </div>
</div>


</body>
</html>


		Historial de compras:
		{% for histo in historial %}
		
			{% if histo %}
			
					 Producto: {{ histo.idProducto.nombre }} <br>
			{% else %}
			{% endif %}
		{% endfor %}
		
		
		
		
		{% for fech in fecha %}
		Fecha: {{ fech.idUsuario.nombre}}
		{% endfor %}


<body>




</html>

apps/store/templates/store/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}
{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

apps/store/templates/store/profile.html
<form method="post">
  {% csrf_token %}
  {{ user_form.as_p }}
  {{ profile_form.as_p }}
  <button type="submit">Save changes</button>
</form>

apps/store/templates/store/shopping_cart.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">


<!DOCTYPE html>
<html>
<head>
<!-------------------------MENU STYLE------------------------>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
    margin-bottom: 0
}
li {
    float: left;
}
li a {
    display: inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}
li a:hover:not(.active) {
    background-color: #111;
}
.active {
    background-color: #4CAF50;
}
.logo-img {
	display:inline-block;
    float:left
    position:absolute;
    left:10px;
    top:1px;
    margin: 0px 1px 1px 0px;
    float: left;
}
</style>
<!------------------------END MENU STYLE------------------------>



<!-------------------------GRID STYLE------------------------>
<style>
.item1 { grid-area: header; }
.item2 { grid-area: menu; }
.item3 { grid-area: main; }
.item4 { grid-area: right; }
.item5 { grid-area: footer; }

.grid-container {
  display: grid;
  grid-template-areas:
    'header header header header header header'
    'menu main main main main main'
    'menu footer footer footer footer footer';
  grid-gap: 1px;
  background-color: rgba(255, 255, 255);
  padding: 10px;
}
.grid-container > div {
  background-color: rgba(255, 255, 255);
  text-align: center;
  padding: 20px 0;
  font-size: 30px;
}
</style>
<!-------------------------END GRID STYLE------------------------>


<!-------------------------PRODUCT GRID STYLE------------------------>
<style>
.grid-container2 {
  display: grid;
  grid-template-columns: auto auto auto;
  background-color: rgba(255, 255, 255);
  padding: 10px;
}
.grid-item2 {
  background-color: rgba(255, 255, 255);
  border: 0px solid rgba(0, 0, 0);
  padding: 20px;
  font-size: 30px;
  text-align: center;
}
</style>
<!-------------------------END PRODUCT GRID STYLE------------------------>




</head>
<body>


<div class="grid-container">
  <div class="item1"><ul>
  <li><a href="/home.html">Home</a></li>
  <li><a href="#news">News</a></li>
  <li><a href="#contact">Contact</a></li>
  <li><a href="#ingresar">Ingresar</a></li>
  <li style="float:right"><a class="active" href="#carrito">Carrito</a></li>
</ul>
</div>


  <div class="item2"><img class="logo-img" src="/apps/store/static/baraticoCLOUD.gif" alt="El Baratico" width="400" height="500"></div>
  <table style="width:100%">
  <tr>
    <th>Cantidad</th>
    <th>Producto</th> 
    <th>Precio Unitario</th>
    <th>Precio Total</th>
    <th>Eliminar producto</th>
  </tr>
  {% if productos %}
    {% for producto in productos %}
      <tr>
        <th> 1 </th>
        <th> {{ producto.nombre }} </th> 
        <th> {{ producto.precio }} </th>
        <th> {{ producto.precio }} </th>
        <th> <a href="{% url 'store:delete_cart_item' producto.id %}">   Eliminar </a> </th> 
      </tr>
    {% endfor %}
  {% else %}
  {% endif %}

</table>
<br>
<a href="{% url 'store:delete_all_cart_items' %}">   Comprar </a>

</body>
</html>



<!DOCTYPE html>
<html>
<head>





</head>


<body>




</html>

apps/store/templates/store/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}